mm: mm_init, readme.md

diff --git a/bin/include b/bin/include
--- a/bin/include
+++ b/bin/include
@@ -23,6 +23,18 @@ check_dependencies()
 	done
 }
 
+mm_init()
+{
+	if [ ! -d $logdir ]; then
+		dialog --title "Memo Menu" --yesno "Directory '$logdir' does not exist. Would you like to create it now?" $def_h $def_w 2> /dev/null
+		if [ $? -eq 0 ]; then
+			mkdir $logdir
+		else
+			die "Could not open directory '$logdir'"
+		fi
+	fi
+}
+
 # Remove extra archives
 # arch_keep NUMBERARCHIVES
 arc_keep()
