mm_init: create missing directories on startup

diff --git a/bin/include b/bin/include
--- a/bin/include
+++ b/bin/include
@@ -25,12 +25,25 @@ check_dependencies()
 
 mm_init()
 {
+	# Check if logdir exists
 	if [ ! -d $logdir ]; then
 		dialog --title "Memo Menu" --yesno "Directory '$logdir' does not exist. Would you like to create it now?" $def_h $def_w 2> /dev/null
 		if [ $? -eq 0 ]; then
 			mkdir $logdir
+			#mkdir $logdir/$(date +'%y')
 		else
 			die "Could not open directory '$logdir'"
+		fi
+	fi
+
+	# Check if arcdir exists
+	if [ ! -d $arcdir ]; then
+		dialog --title "Memo Menu" --yesno "Directory '$arcdir' does not exist. Would you like to create it now?" $def_h $def_w 2> /dev/null
+		if [ $? -eq 0 ]; then
+			mkdir $arcdir
+			#mkdir $arcdir/$(date +'%y')
+		else
+			die "Could not open directory '$arcdir'"
 		fi
 	fi
 }
